import React, { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { scrollToTop } from '../../utils';

const Condition = () => {
  const { lang } = useSelector((state) => state.lang);
  useEffect(() => {
    scrollToTop();
  }, [])
  return (
    <section>
      <div className="py-16">
        <div className="container text-white py-12 px-4">
          <h3 className="text-2xl font-semibold mb-10">{lang === 'eng' ? 'TERMS AND CONDITIONS' : 'УСЛОВИЯ И ПОЛОЖЕНИЯ'}</h3>
          <p className="text-md font-semibold mb-4">{lang === 'eng' ? 'The Lessor mentioned overleaf, called Terra Car Rental, hereby rents vehicle identified overleaf to Renter subject to all terms and conditions on the front page and this page and the Renter, on consideration thereof agrees to them as the essence of the agreement.': 'Арендодатель, упомянутый на оборотной стороне, под названием Terra Car Rental, настоящим сдает в аренду Транспортное средство, указанное на оборотной стороне, Арендатору с соблюдением всех условий, указанных на первой странице и на этой странице, и Арендатор, при их рассмотрении, соглашается с ними как с сутью соглашения.' }</p>
          <h4 className="text-xl font-semibold">1. {lang === 'eng' ? 'Delivery and Return' : 'Доставка и возврат'}</h4>
          <p className="text-md mt-4">{lang === 'eng' ? 'The vehicle is delivered to the Renter in good overall condition and without apparent defects. Any complaints as to its condition must be made to the Lessor immediately upon delivery. The Renter agrees to return it with all documents and accessories and in the same condition to the Lessor at the location and on the date designated in this agreement. The Lessor reserves the right to repossess the vehicle without demand at Renter’s expense if vehicle is used in violation of this agreement.' : 'Автомобиль передается Арендатору в хорошем общем состоянии и без видимых дефектов. Любые жалобы на его состояние должны быть предъявлены Арендодателю сразу после доставки. Арендатор обязуется вернуть его со всеми документами и принадлежностями и в том же состоянии Арендодателю по месту и в дату, указанные в настоящем договоре. Арендодатель оставляет за собой право без предъявления требования вернуть себе транспортное средство за счет Арендатора, если транспортное средство используется с нарушением настоящего договора.'}</p>
          <h4 className="text-xl font-semibold mt-6">2. {lang === 'eng' ?  'Damage, Loss, Theft etc.' : 'Повреждение, потеря, кража и т. д.'}</h4>
          <p className="text-md mt-4">{lang === 'eng' ? 'In the event of damages or loss of the vehicle or parts of it, including fire and breakage of glass, the Renter shall irrespective of his or the driver’s fault, pay the amount of all resulting loss and expenses to the Lessor (including but not limited to replacement or recovery costs, repair costs, compensation for decline in value and loss of the rental fee). If Standard Terms and Conditions of Rent are violated, any legal provisions (as well as customs regulations or insurance regulations) of loss of revenue the Lessor may charge a compensation corresponding to the rental charge, until the day the vehicle or a replacement vehicle will again be available to the Leas or. This liability of the Renter may be waived if renter accepts Loss Damage Waiver according to Clause 10 by placing his signature in the space “Accept” on the front page, provided that the renter complies in all other respects with the terms and conditions of this Rental Agreement.' : 'В случае повреждения или утраты транспортного средства или его частей, в том числе возгорания и разбития стекол, Арендатор обязан независимо от своей вины или вины водителя возместить Арендодателю сумму всех возникших в результате убытков и расходов (включая, помимо прочего, затраты на замену или восстановление, затраты на ремонт, компенсацию снижения стоимости и потерю арендной платы). В случае нарушения Стандартных условий аренды, любых правовых положений (а также таможенных правил или правил страхования) в случае потери дохода Арендодатель может взимать компенсацию, соответствующую арендной плате, до того дня, пока транспортное средство или замещающее транспортное средство снова не станет доступным для Арендодателя или. От этой ответственности Арендатора можно отказаться, если Арендатор принимает отказ от возмещения убытков в соответствии с пунктом 10, поставив свою подпись в поле «Принимаю» на первой странице, при условии, что Арендатор соблюдает во всех других отношениях положения и условия настоящего Договора аренды.'}</p>
          <h4 className="text-xl font-semibold mt-6">3.{lang === 'eng' ? 'Charges' : 'Сборы'}</h4>
          <p className="text-md mt-4">{lang === 'eng' ? 'Renter shall pay any charges shown on the page or mentioned in the current tariffs. a) The Cash deposit will be returned after 21 working days. b) The Customer has to pay all the expenses (damage, traffic fines, fuel) if the sum of the charges is more than 30% of the deposit.' : 'Арендатор обязан оплатить любые сборы, указанные на странице или указанные в текущих тарифах. а) Денежный депозит будет возвращен через 21 рабочий день. б) Клиент обязан оплатить все расходы (ущерб, штрафы ГИБДД, топливо), если сумма сборов превышает 30% от депозита.'}</p>
          <h4 className="text-xl font-semibold mt-6">4.{ lang === 'eng' ?  'Indemnity' : 'Возмещение' }</h4>
          <p className="text-md mt-4">{ lang === 'eng' ? 'The Lessor is only responsible for loss or damage suffered by Renter or Third Parties, if such loss or damage was caused intentionally or through negligence on Lessor’s part. In all other cases, the Lessor cannot accept any liability and shall be immune against such claims' :  'Арендодатель несет ответственность только за убытки или ущерб, понесенные Арендатором или Третьими лицами, только если такие убытки или ущерб были причинены умышленно или по халатности со стороны Арендодателя. Во всех других случаях Арендодатель не может нести никакой ответственности и имеет иммунитет от таких претензий'}.</p>
          <h4 className="text-xl font-semibold mt-6">5. { lang === 'eng' ? 'Conditions of use' : 'Условия использования'}</h4>
          <p className="text-md mt-4">{ lang === 'eng' ? '– Rented vehicles are not to be driven while Renter or any other driver of vehicle is under the influence of alcohol, hallucinatory drugs, narcotics, barbiturates, or any other substance impairing consciousness or ability to react. Rented vehicles are not to be driven in contravention of any customs, traffic or other regulations;' : '– Запрещается управлять арендованным транспортным средством, если Арендатор или любой другой водитель транспортного средства находится под воздействием алкоголя, галлюцинаторных препаратов, наркотиков, барбитуратов или любого другого вещества, нарушающего сознание или способность реагировать. Арендованные транспортные средства не должны эксплуатироваться с нарушением таможенных, дорожных и других правил;'}</p>
        </div>
      </div>
    </section>
  )
}

export default Condition